services:
  app:
    build:
      context: ../../
      dockerfile: frontend/.devcontainer/Dockerfile
    image: mail_categorizer_frontend_dev:latest
    container_name: mail_categorizer_frontend_dev
    volumes:
      - ../../:/app:cached
    working_dir: /app
    command: sleep infinity
