name: ci-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  test-apiserver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      
      - name: Install Dependencies
        run: |
          cd apiserver
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          cd apiserver/resources/scripts
          chmod +x ./test.sh
          ./test.sh

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6